[package]
name = "mustafa_art"
version = "0.1.0"
edition = "2021"
description = "A simple library for modelling artistic colors"
license = "MIT"
[dependencies]
[profile.dev]
opt-level = 1
[profile.release]
opt-level = 3
